[package]
name = "csqrl/basicstate"
description = "Really simple state management"
version = "0.2.3"
license = "MIT"
authors = ["csqrl (https://csqrl.dev)"]
contributors = ["boatbomber", "rimuy", "gaffal"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dev-dependencies]
TestEZ = "roblox/testez@^0.4.1"
Roact = "roblox/roact@^1.4.3"
