[package]
name = "csqrl/basicstate"
description = "Really simple state management"
version = "0.2.5"
license = "MIT"
authors = ["csqrl (https://csqrl.dev)"]
contributors = ["boatbomber", "rimuy", "gaffal", "mkargus"]
registry = "https://github.com/upliftgames/wally-index"
realm = "shared"

[dev-dependencies]
TestEZ = "roblox/testez@^0.4.1"
